# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d082f31737cbd1c5267f5d951a8ef284c632ac10d6e9db2e7474cbc97c2eb7a0b10272b1f83dda3dcf5a08945481e35e9110d4a65b08d32efa4ea8a24e81326

test:
  secret_key_base: c35c8f6763e461f04dbc0773b3adfcd476c295b2f9083969b04ae30e99f71f1e8102094d40b9a4e53af3333f8430d01193cba6de2fabcf9387abb85fb96265e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
